# Generated by Django 5.0.7 on 2024-08-22 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='fiscal_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='registration_number',
        ),
    ]
