# Generated by Django 5.1.1 on 2024-09-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuySell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_base64', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IvaSalesTestimony',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_base64', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityNotices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_base64', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTestimony',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_base64', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
